import type { BuiltQuestion } from './build.ts';

/**
 * The current storage shape, 1-based string index and all, so regenerating diffs on
 * content rather than format. Changing the shape is a separate, reviewable change.
 */
export function renderQuestions(questions: BuiltQuestion[], edition: string): string {
  const body = questions
    .map((question) => JSON.stringify(question, null, 2).split('\n').map((line) => `  ${line}`).join('\n'))
    .join(',\n');

  return `// Generated by @kviz/importer from the official question bank.
// Edition ${edition}. Do not edit by hand: run \`npm run import -w @kviz/importer\`.
//
// Alternatives no longer carry their "A) " prefix. The app shuffles them, so the letters
// were appearing out of order on screen.

import type { Question } from './types';

export const questions: Question[] = [
${body}
];
`;
}

export interface ImageFile {
  /** As \`imageFileName\` produces it: t30-q4-c. */
  name: string;
  /** The file on disk, extension included: t30-q4-c.jpg. */
  file: string;
}

/** Built from a directory listing, not from what the fetch step believed it wrote. */
export function imagePathFrom(files: ImageFile[], directory = '/images/questions'): (name: string) => string | null {
  const byName = new Map(files.map(({ name, file }) => [name, `${directory}/${file}`]));

  return (name) => byName.get(name) ?? null;
}

export interface Validation {
  problems: string[];
}

/** Checked before writing, because PDF parsing is fragile. */
export function validate(questions: BuiltQuestion[], onDisk: Set<string>): Validation {
  const problems: string[] = [];
  const say = (message: string) => problems.push(message);

  if (questions.length !== 300) say(`expected 300 questions, built ${questions.length}`);

  const topics = new Set(questions.map((q) => `${q.category}-${q.subCategory}`));
  if (topics.size !== 30) say(`expected 30 topics, found ${topics.size}`);

  questions.forEach((question, index) => {
    const where = `question ${index + 1} ("${question.question.slice(0, 40)}…")`;

    if (question.answers.length !== 4) say(`${where} has ${question.answers.length} alternatives`);
    if (question.answers.some((answer) => !answer.trim())) say(`${where} has an empty alternative`);
    if (new Set(question.answers).size !== question.answers.length) say(`${where} repeats an alternative`);

    const correct = Number(question.correctAnswer);
    if (!Number.isInteger(correct) || correct < 1 || correct > question.answers.length) {
      say(`${where} has correctAnswer ${question.correctAnswer}, outside 1..${question.answers.length}`);
    }

    const pictures = [
      ...(question.questionType === 'photo' ? question.answers : []),
      ...(question.questionPic ? [question.questionPic] : []),
    ];

    pictures.forEach((path) => {
      if (!onDisk.has(path.split('/').pop()!)) say(`${where} wants ${path}, which is not on disk`);
    });
  });

  return { problems };
}
