import { commonsFileUrl } from './citations.ts';
import { imageFileName } from './build.ts';
import type { Citation } from './citations.ts';

/** Formats Commons serves that a browser can put in an <img>. */
const USABLE = ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp'];

/** Asking Commons for a width rasterises SVG to PNG: bigger, and worse for a flag. */
const VECTOR = 'svg';

/** Commons serves originals: 105MB for the set, several photographs over 10MB each. */
const WIDTH = 800;

/**
 * Names the layout broke beyond what stripping spaces fixes. A table, not a heuristic:
 * a guessed file name illustrates a question with the wrong photograph. Verify against
 * Commons, and open the picture, before adding one.
 */
const CORRECTIONS: Record<string, string> = {
  // Wrapped inside the date, losing a hyphen. Printed name 404s; this one resolves.
  'Praha_2005-0920_národní_divadlo.jpg': 'Praha_2005-09-20_národní_divadlo.jpg',
};

export interface PictureProblem {
  citation: Citation;
  reason: string;
}

/** Extension comes from the Commons name, so the file is named before anything is fetched. */
export function pictureSource(citation: Citation): { url: string; extension: string } | { reason: string } {
  const name = CORRECTIONS[citation.source] ?? citation.source;

  if (name.includes('://')) {
    // A page on another site, not a file. Only a person can follow that.
    return { reason: `not a Wikimedia Commons file: ${name}` };
  }

  const extension = name.split('.').pop()?.toLowerCase() ?? '';

  if (!USABLE.includes(extension)) {
    return { reason: `Commons name has no usable file extension: ${name}` };
  }

  const url = commonsFileUrl(name);

  return {
    url: extension === VECTOR ? url : `${url}?width=${WIDTH}`,
    extension,
  };
}

export interface PictureDeps {
  /** Returns the bytes, or says why it could not. Never throws. */
  download: (url: string) => Promise<{ ok: true; bytes: Uint8Array } | { ok: false; reason: string }>;
  write: (fileName: string, bytes: Uint8Array) => Promise<void>;
  /** Called before each download. */
  onProgress?: (message: string) => void;
}

export interface SavedPictures {
  /** Keyed by `imageFileName`, valued by the file actually written, extension included. */
  files: Map<string, string>;
  problems: PictureProblem[];
}

/**
 * Downloads each cited picture, named after its question.
 *
 * The bank names files by position — `17alt3.jpg` is topic 17, alternative 3 — so
 * renumbering silently repoints them; four answers once showed presidents instead of a
 * theatre. Sequential, since this is somebody else's server.
 */
export async function savePictures(
  citations: Citation[],
  { download, write, onProgress }: PictureDeps,
): Promise<SavedPictures> {
  const files = new Map<string, string>();
  const problems: PictureProblem[] = [];

  for (const citation of citations) {
    const name = imageFileName(citation);

    // Two questions can cite the same Commons file.
    if (files.has(name)) continue;

    const source = pictureSource(citation);

    if ('reason' in source) {
      problems.push({ citation, reason: source.reason });
      continue;
    }

    const file = `${name}.${source.extension}`;
    onProgress?.(`${file}  ←  ${citation.source}`);

    const result = await download(source.url);

    if (!result.ok) {
      problems.push({ citation, reason: result.reason });
      continue;
    }

    await write(file, result.bytes);
    files.set(name, file);
  }

  return { files, problems };
}

/** Credits, as the licences require. Keyed by the written file, so it checks against disk. */
export function attribution(citations: Citation[], files: Map<string, string>): string {
  const lines = [
    '# Picture credits',
    '',
    'Generated by @kviz/importer. Each picture as the official question bank credits it,',
    'with the Wikimedia Commons file it came from.',
    '',
    '| File | Commons | Credit |',
    '|---|---|---|',
  ];

  const seen = new Set<string>();

  for (const citation of citations) {
    const file = files.get(imageFileName(citation));
    if (!file || seen.has(file)) continue;

    seen.add(file);
    lines.push(`| \`${file}\` | [${citation.source}](${commonsFileUrl(citation.source)}) | ${citation.credit} |`);
  }

  return `${lines.join('\n')}\n`;
}
