import { questions } from './questions';

export const quiz =  {
    "quizTitle": "React Quiz Component Demo",
    "appLocale": {
        landingHeaderText: 'Množství otázek: <questionLength>',
        question: 'Otázky',
        startQuizBtn: 'Spustit kvíz',
        resultFilterAll: 'Vše',
        resultFilterCorrect: 'Správně',
        resultFilterIncorrect: 'Nesprávně',
        resultFilterUnanswered: 'Nezodpovězeno',
        nextQuestionBtn: 'Další',
        prevQuestionBtn: 'Předchozí',
        resultPageHeaderText: 'Dokončil(a) jste kvíz. Máte spravně <correctIndexLength> z <questionLength> otázek.',
        resultPagePoint: 'Získal(a) jste <correctPoints> z <totalPoints> bodů.',
        pauseScreenDisplay: 'Test je pozastaven. Klikněte na tlačítko Obnovit pro pokračování.',
        timerTimeRemaining: 'Zbývající čas',
        timerTimeTaken: 'Časový limit',
        pauseScreenPause: 'Pauza',
        pauseScreenResume: 'Obnovit',
        singleSelectionTagText: 'Jedna správná odpověď',
        multipleSelectionTagText: 'Více správných odpovědí',
        pickNumberOfSelection: 'Vyberte <numberOfSelection>',
        marksOfQuestion: '(<marks> Body)',
    },
    "quizSynopsis": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim",
    "progressBarColor": "#9de1f6",
    "questions": questions,
}
